config/routes.rb
JgcMapping::Application.routes.draw do |map|

  match '/programs/associate' => 'programs#associate'

  resources :categories

  resources :styles

  resources :repeats

  resources :programs

  resources :service_people

  resources :service_groups

  

  match '/visualize' => 'visualizer#index'
  match '/visualize/:action/(:id)' => 'visualizer#view/(:id)'
  match '/find' => 'visualizer#advanced_find'
  match '/visualize/method_missing' => 'admin#invalid_request'
  match '/admin/:action' => 'admin#view'
  match '*path' => 'admin#invalid_request'

  root :to => "visualizer#index"

end

app/models/service_group.rb
class ServiceGroup < ActiveRecord::Base
  has_many :service_persons
  has_many :programs

  before_validation :capitalize_state
  before_destroy :check_for_actives

  validates_presence_of :name
  validates_presence_of :address1
  validates_presence_of :city
  validates_presence_of :state
  validates :state, :state => true
  validates :zip, :length => {:minimum => 5, :maximum => 10}
  

  def capitalize_state
    self.state = self.state.upcase unless self.state.nil?
  end

  def check_for_actives
    if (self.service_persons.count + self.programs.count) > 0
      errors[:base] << "People and/or programs are still associated with this group, so it cannot be deleted"
      false
    end
  end
end

app/controllers/service_groups_controller.rb
class ServiceGroupsController < ApplicationController
  # GET /service_groups
  # GET /service_groups.xml

  before_filter :authorize_admin, :except => [:index, :show]

  def index
    @service_groups = ServiceGroup.order('name ASC')

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @service_groups }
    end
  end

  # GET /service_groups/1
  # GET /service_groups/1.xml
  def show
    begin
      @service_group = ServiceGroup.find(params[:id])
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @service_group }
      end
    rescue
      invalid_route
    end
  end

  # GET /service_groups/new
  # GET /service_groups/new.xml
  def new
    @service_group = ServiceGroup.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @service_group }
    end
  end

  # GET /service_groups/1/edit
  def edit
    begin
      @service_group = ServiceGroup.find(params[:id])
    rescue
      invalid_route
    end
  end

  # POST /service_groups
  # POST /service_groups.xml
  def create
    @service_group = ServiceGroup.new(params[:service_group])

    respond_to do |format|
      if @service_group.save
        format.html { redirect_to(@service_group, :notice => 'Service group was successfully created.') }
        format.xml  { render :xml => @service_group, :status => :created, :location => @service_group }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @service_group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /service_groups/1
  # PUT /service_groups/1.xml
  def update
    @service_group = ServiceGroup.find(params[:id])

    respond_to do |format|
      if @service_group.update_attributes(params[:service_group])
        format.html { redirect_to(@service_group, :notice => 'Service group was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @service_group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /service_groups/1
  # DELETE /service_groups/1.xml
  def destroy
    @service_group = ServiceGroup.find(params[:id])
    result = @service_group.destroy
    flash[:notice] = @service_group.errors[:base][0] if result == false

    respond_to do |format|
      format.html { redirect_to(service_groups_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/service_groups_helper.rb
module ServiceGroupsHelper
end

app/views/service_groups/_form.html.erb
<%= form_for(@service_group) do |f| %>
  <% if @service_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service_group.errors.count, "error") %> prohibited this service_group from being saved:</h2>

      <ul>
      <% @service_group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address1 %><br />
    <%= f.text_field :address1 %>
  </div>
  <div class="field">
    <%= f.label :address2 %><br />
    <%= f.text_field :address2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :inception_date %><br />
    <%= f.date_select :inception_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/service_groups/edit.html.erb
<h1>Editing service_group</h1>

<%= render 'form' %>

<%= link_to 'Show', @service_group %> |
<%= link_to 'Back', service_groups_path %>

app/views/service_groups/index.html.erb
<h1>Listing service_groups</h1>

<p id="notice"><%= notice %></p>

<table>
  <tr class='heading'>
    <th>Name</th>
    <th>Address1</th>
    <th>Address2</th>
    <th>City</th>
    <th>State</th>
    <th>Zip</th>
    <th>Phone</th>
    <th>Website</th>
    <th>Inception date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @service_groups.each do |service_group| %>
  <tr class='<%= cycle("odd","even") %>'>
    <td><%= service_group.name %></td>
    <td><%= service_group.address1 %></td>
    <td><%= service_group.address2 %></td>
    <td><%= service_group.city %></td>
    <td><%= service_group.state %></td>
    <td><%= service_group.zip %></td>
    <td><%= service_group.phone %></td>
    <td><%= service_group.website %></td>
    <td><%= service_group.inception_date %></td>
    <td><%= link_to 'Show', service_group %></td>
    <% if session[:admin_user] == "1" %>
      <td><%= link_to 'Edit', edit_service_group_path(service_group) %></td>
      <td><%= link_to 'Destroy', service_group, :confirm => 'Are you sure?', :method => :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<% if session[:admin_user] == "1" %>
  <%= link_to 'New Service group', new_service_group_path %>
<% end %>

app/views/service_groups/new.html.erb
<h1>New service_group</h1>

<%= render 'form' %>

<%= link_to 'Back', service_groups_path %>

app/views/service_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @service_group.name %>
</p>

<p>
  <b>Address1:</b>
  <%= @service_group.address1 %>
</p>

<p>
  <b>Address2:</b>
  <%= @service_group.address2 %>
</p>

<p>
  <b>City:</b>
  <%= @service_group.city %>
</p>

<p>
  <b>State:</b>
  <%= @service_group.state %>
</p>

<p>
  <b>Zip:</b>
  <%= @service_group.zip %>
</p>

<p>
  <b>Phone:</b>
  <%= @service_group.phone %>
</p>

<p>
  <b>Website:</b>
  <%= @service_group.website %>
</p>

<p>
  <b>Inception date:</b>
  <%= @service_group.inception_date %>
</p>


<% if session[:admin_user] == "1" %>
  <%= link_to 'Edit', edit_service_group_path(@service_group) %> |
<% end %>
<%= link_to 'Back', service_groups_path %>