config/routes.rb
JgcMapping::Application.routes.draw do |map|

  match '/programs/associate' => 'programs#associate'

  resources :categories

  resources :styles

  resources :repeats

  resources :programs

  resources :service_people

  resources :service_groups

  

  match '/visualize' => 'visualizer#index'
  match '/visualize/:action/(:id)' => 'visualizer#view/(:id)'
  match '/find' => 'visualizer#advanced_find'
  match '/visualize/method_missing' => 'admin#invalid_request'
  match '/admin/:action' => 'admin#view'
  match '*path' => 'admin#invalid_request'

  root :to => "visualizer#index"

end

app/views/admin/_form.html.erb
<%= form_tag "/admin/process_login", :method => :post do %>

  <div class="field">
    <%= label :login, :email %><br />
    <%= text_field :login, :email %>
  </div>
  <div class="field">
    <%= label :login, :password %><br />
    <%= password_field :login, :password %>
  </div>
  <div class="actions">
    <%= submit_tag 'Submit' %>
  </div>
<% end %>

app/views/admin/invalid_request.html.erb
Invalid request

app/views/admin/login.html.erb
<h1>Please login to be granted administrative capabilities</h1>

<p id="notice"><%= notice %></p>

<%= render 'form' %>

app/views/admin/process_login.html.erb
  <div id='notice'>You are authorized as an administrator for this session</div>

  <h2>Click on an element to view/edit/delete</h2>
  <%= link_to 'Service groups', service_groups_path %><br />
  <%= link_to 'Service people', service_people_path %><br />
  <%= link_to 'Programs', programs_path %><br />
  <hr />
  <h2>Configurable data elements</h2>
  <%= link_to 'Program schedule options', repeats_path %><br />
  <%= link_to 'Program formats', styles_path %><br />
  <%= link_to 'Program categories', categories_path %><br />