config/routes.rb
JgcMapping::Application.routes.draw do |map|

  match '/programs/associate' => 'programs#associate'

  resources :categories

  resources :styles

  resources :repeats

  resources :programs

  resources :service_people

  resources :service_groups

  

  match '/visualize' => 'visualizer#index'
  match '/visualize/:action/(:id)' => 'visualizer#view/(:id)'
  match '/find' => 'visualizer#advanced_find'
  match '/visualize/method_missing' => 'admin#invalid_request'
  match '/admin/:action' => 'admin#view'
  match '*path' => 'admin#invalid_request'

  root :to => "visualizer#index"

end

app/models/program.rb
class Program < ActiveRecord::Base
  has_one :service_group
  has_one :repeat
  has_and_belongs_to_many :service_persons
  has_and_belongs_to_many :categories
  has_and_belongs_to_many :styles
  has_many :served_areas
 
  before_validation :capitalize_state
  before_save :create_formatted_address, :get_lat_lon, :create_formatted_characteristics, :hyperlink_url

  validates_presence_of :service_group_id, :message => "must be selected"
  validates_presence_of :name
  validates_numericality_of :start_time, :less_than_or_equal_to => 24, :allow_blank => true
  validates_numericality_of :end_time, :less_than_or_equal_to => 24, :allow_blank => true #ideally would check if end date same, then make sure later than start_time
  validates_presence_of :end_date, :greater_than_or_equal_to => :start_date
  validate :validate_date_combination
  validates_presence_of :address1
  validates_presence_of :city
  validate :state, :state => true
  validates :zipcode, :length => {:minimum => 5, :maximum => 10}
  validates_associated :styles
  validates_associated :service_persons
  validates_associated :categories

  private

  def validate_date_combination
    begin
      errors.add(:start_date, "can not be after end date") unless self.start_date <= self.end_date
    rescue
      errors.add(:start_date, "may be invalid") 
      errors.add(:end_date, "may be invalid") 
    end
  end

  def capitalize_state
    self.state = self.state.upcase unless self.state.nil?
  end
     

  def within_miles(radius)
    self.class.within_miles_of_zip(radius, zip)
  end

  def create_formatted_address
    self.formatted_address = self.address1
    unless self.address2.nil? || self.address2.blank?
      self.formatted_address += " " + self.address2 + ", "
    else
      self.formatted_address += ", "
    end
    self.formatted_address += self.city + ", " + self.state + ", " + self.zipcode + ", USA"
  end

  def create_formatted_characteristics #JBB Need a script to assign all programs to an existing repeats ID.
    self.formatted_repeats = REPEATS_HASH[self.repeats]
    self.formatted_categories = ""
    self.categories.each_with_index do |category,index|
      self.formatted_categories += category.name
      self.formatted_categories += ", " unless index == self.categories.length - 1
    end
    self.formatted_styles = ""
    self.styles.each_with_index do |style,index|
      self.formatted_styles += style.name
      self.formatted_styles += ", " unless index == self.styles.length - 1
    end
    unless self.start_time.nil? || self.end_time.nil?
      #need to pad zeros or get 16:0
      unless self.start_time > self.end_time
        self.formatted_hours = pretty_time(self.start_time)
        #self.formatted_hours = self.start_time.to_s.gsub(".",":")
        #post_decimal = self.formatted_hours[/\:\d+/]
        #if post_decimal && post_decimal.length == 2
        #  self.formatted_hours += "0"
        #end
        self.formatted_hours += " - "
        self.formatted_hours += pretty_time(self.end_time)
        #self.formatted_hours += " - "
        #self.formatted_hours += self.end_time.to_s.gsub(".",":")
        #post_decimal = end_time.to_s[/\.\d+/]
        #if post_decimal && post_decimal.length == 2
        #  self.formatted_hours += "0"
        #end
      end
    else
      self.formatted_hours = ""
    end
  end

  def hyperlink_url
    unless self.website.blank?
      self.website = "http://" + self.website unless self.website[/^http/]
    end

  end

  ###This method is called anytime a program is created or updated and it uses the google maps API
  ###to insert lat and lon values into the program db record
  def get_lat_lon
    begin
      require 'net/http'
      uri1 = "maps.google.com"
      uri2 = "/maps/api/geocode/json?address=#{self.formatted_address.gsub(/\s/,'+')}&sensor=false"
      json_lat_lon = Net::HTTP.get_response(uri1,uri2)
      @json_lat_lon = ActiveSupport::JSON.decode json_lat_lon.body
      if @json_lat_lon["status"] == "OK"
        self.lat = @json_lat_lon["results"][0]["geometry"]["location"]["lat"]
        self.lon = @json_lat_lon["results"][0]["geometry"]["location"]["lng"]
      end
    rescue
      errors.add(:lat, "problem retrieving lat/long")
    end
  end

  def pretty_time(time)
    time > 12 ? new_time = time - 12 : new_time = time
    new_time = new_time.to_s
    new_time.gsub!(".",":")
    post_decimal = new_time[/\:\d+/]
    if post_decimal && post_decimal.length == 2
      new_time += "0"
    end
    if time < 12
      new_time += " AM"
    else
      new_time += " PM"
    end
    new_time
  end

end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  # GET /programs
  # GET /programs.xml

  before_filter :authorize_admin, :except => [:index, :show]

  def index
    @programs = Program.order('name ASC')
    @repeat_options = REPEATS_HASH

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @programs }
    end
  end

  # GET /programs/1
  # GET /programs/1.xml
  def show
    begin
      @program = Program.find(params[:id])
      format_additional_areas_served
      load_many_to_many

      respond_to do |format|
        format.html 
        format.xml  { render :xml => @program }
      end
    rescue
      invalid_route
    end
  end

  # GET /programs/new
  # GET /programs/new.xml
  def new
    @program = Program.new
    @active_categories = []
    @active_styles = []
    @active_service_people = []
    @service_people = []
    @more_served_areas = ""

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @program }
    end
  end

  # GET /programs/1/edit
  def edit
    begin
      @program = Program.find(params[:id])
      @service_people = ServicePerson.where('service_group_id = ?',@program.service_group_id)
      format_additional_areas_served
      load_many_to_many
    rescue
      invalid_route
    end
  end

  # POST /programs
  # POST /programs.xml
  def create
    params[:program][:category_ids] ||= []
    params[:program][:cost] = "-1" if params[:program][:cost].downcase == "paid"
    params[:program][:cost] = "0" if params[:program][:cost].downcase == "free"
    params[:program][:cost].gsub!("$","") if params[:program][:cost][/\$/]
    #handle time inputs
    params[:program][:start_time] = format_time(params[:program][:start_time])
    params[:program][:end_time] = format_time(params[:program][:end_time])
    params[:program][:category_ids].count > 0 ? @is_category = true : @is_category = false
    params[:program][:service_group_id].to_i > 0 ? @is_group = true : @is_group = false
    #zipcode = params[:program][:zipcode]
    #zipcode = zipcode[0,5]
    #zip_obj = Zip.code(zipcode)
    #params[:program][:zip_id] = zip_obj.id unless zip_obj.nil?

    @program = Program.new(params[:program])
    begin
      @service_people = ServicePerson.where('service_group_id = ?',params[:program][:service_group_id])
    rescue
      @service_people = []
    end
    #zip_obj.programs.push(@program)
    #zip = Zip.code(@program.zipcode)
    #unless zip.nil?
    #{
    #  @program.zip_id = zip.id
      #zip.programs.push(@program) #JBB not sure what the intention was here. Jeff?
    #}
    
    load_many_to_many

    respond_to do |format|
      if @program.save && @is_category && @is_group
        handle_additional_areas_served
        format.html { redirect_to(@program, :notice => 'Program was successfully created.') }
        format.xml  { render :xml => @program, :status => :created, :location => @program }
      else
        @program.errors[:base] << 'Please assign one or more categories.' unless @is_category
        format.html { render :action => "new" }
        format.xml  { render :xml => @program.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /programs/1
  # PUT /programs/1.xml
  def update
    params[:program][:category_ids] ||= []
    @program = Program.find(params[:id])
    @service_people = ServicePerson.where('service_group_id = ?',@program.service_group_id)
    @more_served_areas = ""
    load_many_to_many

    params[:program][:cost] = "-1" if params[:program][:cost].downcase == "paid"
    params[:program][:cost] = "0" if params[:program][:cost].downcase == "free"
    params[:program][:cost].gsub!("$","") if params[:program][:cost][/\$/]
    #handle time inputs
    params[:program][:start_time] = format_time(params[:program][:start_time])
    params[:program][:end_time] = format_time(params[:program][:end_time])
    
    handle_additional_areas_served

    respond_to do |format|
      if @program.update_attributes(params[:program]) && params[:program][:category_ids].count > 0
        format.html { redirect_to(@program, :notice => 'Program was successfully updated.') }
        format.xml  { head :ok }
      else
        if params[:program][:category_ids].count < 1
          @program.errors[:base] << 'Please assign one or more categories.' 
        end
        format.html { render :action => "edit" }
        format.xml  { render :xml => @program.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.xml
  def destroy
    @program = Program.find(params[:id])
    @program.destroy

    respond_to do |format|
      format.html { redirect_to(programs_url) }
      format.xml  { head :ok }
    end
  end

  def load_many_to_many
    @active_categories = []
    @program.categories.each do |cat|
      @active_categories << cat.id
    end
    @active_styles = []
    @program.styles.each do |style|
      @active_styles << style.id
    end
    @active_service_people = []
    @program.service_persons.each do |sp|
      @active_service_people << sp.id
    end
  end

  def handle_additional_areas_served
    begin
      if params[:additional_zips] != params[:additional_zip_original] #remove old, add new
        #If program.update_attributes fails, these additional zips will have made it into the DB anyway
        #delete prior additionals
        result = ServedArea.delete_all(["program_id = ?",@program.id])
        params[:additional_zips].gsub(/\s/,"").split(",").each do |zip|
          if zip != @program.zipcode #no sense in storing it here if program already in that zip
            new_area = ServedArea.new
            new_area.program_id = params[:id]
            new_area.formatted_address = zip.first(5)
            new_area.save
            @more_served_areas += zip.first(5) + ","
          end
        end
       @more_served_areas.gsub!(/,$/,"") 
      end
    rescue
      @more_served_areas = ""
    end
  end

  def format_additional_areas_served
    additional_served_areas = ServedArea.where('program_id = ?',@program.id)
    @more_served_areas = ""
    for area in additional_served_areas
      @more_served_areas += area.formatted_address + ","
    end
    @more_served_areas.gsub!(/,$/,"")
  end

  def associate
    #JBB should not respond to non js queries
    #respond_to :js
    @active_service_people = []
    unless params[:service_group_id].nil? || params[:service_group_id] == ""
      @service_group = ServiceGroup.find(params[:service_group_id]) 
      @service_people = @service_group.service_persons
      if params[:program_id] == ""
        @active_service_people = [] 
      else
        Program.find(params[:program_id]).service_persons.each do |sp|
          @active_service_people << sp.id 
        end
      end
    else
      render :nothing => true 
      #@service_group = ServiceGroup.first
      #@service_people = @service_group.service_persons
    end
    #  render(:update) do |page|
    #    page[:program_address1].value = @program.address1
    #  end
  end

  def format_time(time_string = "") #JBB check on this as default value
    @numeric_time = nil
    if time_string.length > 0
      time_string.downcase =~ /pm/ ? add_twelve = true : add_twelve = false
      time_string.gsub!(":",".")
      @numeric_time = time_string[/\d{1,2}(\.)?(\d{1,2})?/].to_f
      @numeric_time += 12 if add_twelve
    end
    @numeric_time
  end 
  

end

app/helpers/programs_helper.rb
module ProgramsHelper

  def display_cost(amount = nil)
    if amount.nil?
      @display_value = "Unknown"
    elsif amount == 0
      @display_value = "Free"
    elsif amount > 0
      @display_value = number_to_currency(amount)
    else
      @display_value = "Paid"
    end
  end

  #Turn decminal into friendly time
  def decimal_to_24hour_time(t_value)
    @friendly_time = ft = t_value.to_s
    if ft.length > 0
      @friendly_time = ft[/\d{1,2}/] + ":" 
      ft[/\.(\d{1,2})/]
      @friendly_time += $1.to_s unless $1.nil?
      @friendly_time += "0" if (@friendly_time[/:\d{1,2}/].length == 2)
    end
    @friendly_time
  end

end

app/views/programs/_form.html.erb
<img src="/images/blank-dot.png" onload="$('submit-button').hide();">
<div class="field">
  The service group associated with this program:<br />
  <%= form_tag "/programs/associate", :id => "service-group-list", :method => :post, :remote => true do %>
    <% unless @program.nil? %>
      <input type=hidden name="program_id" value=<%= @program.id %>>
    <% end %>
    <select name="service_group_id" id="service_group_id" onchange="$('submit-button').click();">
      <option value="">Please select a service group</option>
    <% for sg in ServiceGroup.order('name ASC') %>
      <% if !(@program.nil?) && sg.id == @program.service_group_id %>
        <option value="<%= sg.id %>" selected="selected"><%= sg.name %></option>
      <% else %>
        <option value="<%= sg.id %>"><%= sg.name %></option>
      <% end %>
    <% end %>
    </select>
    <%= submit_tag "Submit Service Group", :id => "submit-button", :class => "hidden-form-button", :name => nil %>
  <% end %>
</div>

<%= form_for(@program) do |f| %>
  <%= render "shared/error_messages", :target => @program %>
  <%= f.hidden_field :service_group_id %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.date_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br />
    <%= f.text_field :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br />
    <%= f.text_field :end_time %>
  </div>
  <div class="field">
    <%= f.label :repeats %><br />
    <select id="program_repeats" name="program[repeats]">
    <% for repeat in REPEATS %>
      <% if repeat[:id] == @program.repeats %>
        <option value="<%= repeat[:id] %>" selected="selected"><%= repeat[:name] %></option>
      <% else %>
        <option value="<%= repeat[:id] %>"><%= repeat[:name] %></option>
      <% end %>
    <% end %>
    </select>  
  </div>
  <div class="field">
    <%= f.label :range %><br />
    <%= f.date_select :range %>
  </div>
  <div class="field">
    <%= f.label :age_min %><br />
    <%= f.text_field :age_min %>
  </div>
  <div class="field">
    <%= f.label :age_max %><br />
    <%= f.text_field :age_max %>
  </div>
  <div class="field">
    <%= f.label :cost %> (Enter "free", "paid" or an amount)<br />
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :address1 %><br />
    <%= f.text_field :address1 %>
  </div>
  <div class="field">
    <%= f.label :address2 %><br />
    <%= f.text_field :address2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state, {:size => 2} %>
  </div>
  <div class="field">
    <%= f.label :zipcode %><br />
    <%= f.text_field :zipcode %>
  </div>

  <div class="field">
    <label>Additional zip codes served (separate with a ",". E.g., "94303, 94310")</label><br /> 
    <%= text_field_tag "additional_zips",  @more_served_areas %>
  </div>
  <input type=hidden name="additional_zip_original" value="<%= @more_served_areas %>">
  
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <label>Categories</label><br /> 
    <% for category in CATEGORIES %>
      <%= check_box_tag "program[category_ids][]", category[:id], @active_categories.include?(category[:id])%>
      <%= category[:name] %><br />
    <% end %>
  </div>
  <div class="field">
    <label>Styles</label><br /> 
    <% for style in STYLES %>
      <%= check_box_tag "program[style_ids][]", style[:id], @active_styles.include?(style[:id])%>
      <%= style[:name] %><br />
    <% end %>
  </div>
  <div id="service-people">
    <div class="field">
      <label>Service people</label><br /> 
      <% for sp in @service_people %>
        <%= check_box_tag "program[service_person_ids][]", sp.id, @active_service_people.include?(sp.id)%>
        <%= sp.first_name %> <%= sp.last_name %><br />
      <% end %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/programs/associate.js.erb
$("service_group_id").value = "<%= @service_group.id %>"
$("program_service_group_id").value = "<%= @service_group.id %>"
$("program_address1").value = "<%= @service_group.address1 %>"
$("program_address2").value = "<%= @service_group.address2 %>"
$("program_city").value = "<%= @service_group.city %>"
$("program_state").value = "<%= @service_group.state %>"
$("program_zipcode").value = "<%= @service_group.zip %>"
$("program_phone").value = "<%= @service_group.phone %>"
$("program_website").value = "<%= @service_group.website %>"
$("service-people").replace("<div id=service-people><div class='field'><label>Service people</label><br /></div>")
<% for sp in @service_people %>
  <% if @active_service_people.include?(sp.id) %>
    $("service-people").insert("<input checked='checked' id='program_service_person_ids' name='program[service_person_ids][]' type='checkbox' value='<%= sp.id %>' />")
  <% else %>
    $("service-people").insert("<input id='program_service_person_ids' name='program[service_person_ids][]' type='checkbox' value='<%= sp.id %>' />")
  <% end %> 
  $("service-people").insert({bottom: "<%= sp.first_name %> <%= sp.last_name %><br />"})
<% end %>

app/views/programs/edit.html.erb
<h1>Editing program</h1>

<%= render 'form' %>

<%= link_to 'Show', @program %> |
<%= link_to 'Back', programs_path %>

app/views/programs/index.html.erb
<h1>Listing programs</h1>

<p id="notice"><%= notice %></p>

<table>
  <tr class='heading'>
    <th>Name</th>
    <th>Description</th>
    <th>Start date</th>
    <th>End date</th>
    <th>Start time</th>
    <th>End time</th>
    <th>Repeats</th>
    <th>Range</th>
    <th>Age min</th>
    <th>Age max</th>
    <th>Cost</th>
    <th>Address1</th>
    <th>Address2</th>
    <th>City</th>
    <th>State</th>
    <th>Zip</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @programs.each do |program| %>
  <tr class='<%= cycle("odd","even") %>'>
    <td><%= program.name %></td>
    <td><%= program.description %></td>
    <td><%= program.start_date %></td>
    <td><%= program.end_date %></td>
    <td><%= decimal_to_24hour_time(program.start_time) %></td>
    <td><%= decimal_to_24hour_time(program.end_time) %></td>
    <td>
      <% unless program.repeats.nil? %>
        <%= @repeat_options[program.repeats] %>
      <% end %>
    </td>
    <td><%= program.range %></td>
    <td><%= program.age_min %></td>
    <td><%= program.age_max %></td>
    <td><%= display_cost(program.cost) %></td>
    <td><%= program.address1 %></td>
    <td><%= program.address2 %></td>
    <td><%= program.city %></td>
    <td><%= program.state %></td>
    <td><%= program.zipcode %></td>
    <td><%= link_to 'Show', program %></td>
    <% if session[:admin_user] == "1" %>
      <td><%= link_to 'Edit', edit_program_path(program) %></td>
      <td><%= link_to 'Destroy', program, :confirm => 'Are you sure?', :method => :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<% if session[:admin_user] == "1" %>
  <%= link_to 'New Program', new_program_path %>
<% end %>

app/views/programs/new.html.erb
<h1>New program</h1>

<%= render 'form' %>

<%= link_to 'Back', programs_path %>

app/views/programs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @program.name %>
</p>

<p>
  <b>Description:</b>
  <%= @program.description %>
</p>

<p>
  <b>Start date:</b>
  <%= @program.start_date %>
</p>

<p>
  <b>End date:</b>
  <%= @program.end_date %>
</p>

<p>
  <b>Start time:</b>
  <%= decimal_to_24hour_time(@program.start_time) %>
</p>

<p>
  <b>End time:</b>
  <%= decimal_to_24hour_time(@program.end_time) %>
</p>

<p>
  <b>Repeats:</b>
  <% unless @program.repeats.nil? %>
    <%= REPEATS_HASH[@program.repeats] %>
  <% end %>
</p>

<p>
  <b>Range:</b>
  <%= @program.range %>
</p>

<p>
  <b>Age min:</b>
  <%= @program.age_min %>
</p>

<p>
  <b>Age max:</b>
  <%= @program.age_max %>
</p>

<p>
  <b>Cost:</b>
  <%= display_cost(@program.cost) %>
</p>

<p>
  <b>Address1:</b>
  <%= @program.address1 %>
</p>

<p>
  <b>Address2:</b>
  <%= @program.address2 %>
</p>

<p>
  <b>City:</b>
  <%= @program.city %>
</p>

<p>
  <b>State:</b>
  <%= @program.state %>
</p>

<p>
  <b>Zip:</b>
  <%= @program.zipcode %>
</p>

<p>
  <b>Additional zip codes served:</b>
  <%= @more_served_areas %>
</p>

<p>
  <b>Phone:</b>
  <%= @program.phone %>
</p>

<p>
  <b>Website:</b>
  <%= @program.website %>
</p>

<p>
  <b>Categories:</b>
  <%= @program.categories.collect(&:name).join(', ') %>
</p>
<p>
  <b>Styles:</b>
  <%= @program.styles.collect(&:name).join(', ') %>
</p>
<p>
  <b>Service people:</b>
  <%= @program.service_persons.collect(&:last_name).join(', ') %>
</p>

<% if session[:admin_user] == "1" %>
  <%= link_to 'Edit', edit_program_path(@program) %> |
<% end %>
<%= link_to 'Back', programs_path %>